### PR TITLE
Added a compiled snapshot of the plugin

### PR DESCRIPTION
**Pull request by sgdc3**
I think it's good to provide a snapshot build just for testing.

Gabriele C.

### CODE REVIEW

**Comment by sgdc3** [comment]
I think it's good to provide a snapshot build just for testing.

Gabriele C.

**Comment by sgdc3** [comment]
:/ seems that latest build doesn't work (errors on world creation)

**Comment by timvisee** [comment]
Yes, you're right on that. I'll provide snapshots from now on, great idea. I'll be moving the snapshot binary to a different location in the project though.
I'll take a look into the generation error as soon as possible.

Tim Visée

**Comment by timvisee** [comment]
I can't reproduce the errors on world generation with the latest snapshot, so I think this is fixed. If you're still getting the errors with the latest snapshot, could you please post the error showing up?

Tim Visée

**Comment by sgdc3** [comment]
The error occours only when i execute the generation thru the console.
Error Log: https://gist.github.com/sgdc3/d6e9e2d4700ffbec20f4

**Comment by sgdc3** [comment]
I'm opening a new issue.

**Pull request merged**
