### PR TITLE
Added maven repos + dependencies jars

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by timvisee** [comment]
Thanks for the Maven updates, I don't really use Maven for any project (yet), thus I'm happy you've set it up for Dungeon Maze.

About the version number, shouldn't the 'v' character be removed?

Tim Visée

**Comment by sgdc3** [comment]
If you remove the 'v' from the version number the compiled jar will not have it by default.

**Comment by timvisee** [comment]
I see. I think it's better to remove the 'v' character from the version number and the snapshot jar file, since it isn't included in any of the other version number constants. 

I'll merge the pull request and remove the 'v' sogn manually. 

Tim Visée

**Comment by sgdc3** [comment]
Ok, i agree with you ;)

**Comment by sgdc3** [comment]
Can you set v0.2 as default branch in main page?

**Comment by timvisee** [comment]
Great! As I said, I'll take that task on me, as soon as I've time. (I'm a bit busy at the moment, sorry for that).

I've set the 'v0.2' branch as default for now, this will of course be reverted to the 'master' branch once the current version in development is ready for release.

I've merged this request for now.

Tim Visée

**Pull request merged**
